### ISSUE TITLE
RPC API calculates the last valid block height incorrectly

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#24526]
#### Problem
`Bank::get_blockhash_last_valid_block_height` uses the max age of the blockhash queue to return whether a transaction blockhash is valid but that max age is **double** the max age for transaction processing. RPC API's related to transaction / blockhash expiration use this bank method and give clients an incorrect response. 

#### Proposed Solution
Double the max age of transaction processing (draft PR: https://github.com/solana-labs/solana/pull/24425)

Doubling the max age of transaction processing should increase the chances that user transactions are confirmed even during cluster instability. Validators are already tracking the necessary state for double the current processing age so the implementation requires minimal changes.

tag @t-nelson @mvines @CriesofCarrots

**Comment by jstarry** [comment]
In https://github.com/solana-labs/solana/pull/24425#pullrequestreview-946725407, @t-nelson brought up these concerns:
> [...] this will double (ignoring the ticks bug) the TTL of transactions, which could have some side effects:
> 1. a lot of client SW has dumb human time timeouts. if anyone has a "safe" margin before re-signing a Message, we're going to eat into, if not invalidate it, increasing the risk of a repeat execution.
> 2. transactions lasting longer could prolong the duration of congestion periods given that many bots seem to have little to no stop-logic, at best stopping on expiration
> 3. transactions can remain resident in the RPC STS retry queue for longer, increasing the risk of filling it and dropping new transactions after the initial send rather than retaining them for retry, leading to an inconsistent experience for dapp devs and their users.
> 
> ofc this is all surmountable, but will take some comms effort

**Comment by jstarry** [comment]
> 1. a lot of client SW has dumb human time timeouts. if anyone has a "safe" margin before re-signing a Message, we're going to eat into, if not invalidate it, increasing the risk of a repeat execution.

This is very true but I do think this is already being addressed by efforts to get folks to use the new RPC methods `getLatestBlockhash` and `isBlockhashValid`

> 2. transactions lasting longer could prolong the duration of congestion periods given that many bots seem to have little to no stop-logic, at best stopping on expiration

Since RPC STS behavior won't be changing (explained below), the main impact of doubling the processing age is that the banking stage `filter_pending_packets_from_pending_txs` check will retain more transactions. But this should just be a bit more memory overhead for leaders. Forwards are already throttled.

> 3. transactions can remain resident in the RPC STS retry queue for longer, increasing the risk of filling it and dropping new transactions after the initial send rather than retaining them for retry, leading to an inconsistent experience for dapp devs and their users.

STS already uses `Bank::get_blockhash_last_valid_block_height` which overestimates the actual expiration. So its behavior won't change if we keep the current behavior of `Bank::get_blockhash_last_valid_block_height` as I'm proposing.

**Comment by joncinque** [comment]
This is still an issue, leading people to hack or just ignore the RPC response

**Comment by t-nelson** [comment]
i guess first thing to do here would be to see how frequently `block_height_of(block.contains(tx)) - block_height_of(tx.recent_blockhash) > 150`? assuming it's as low as my intuition tells me it is, reducing `MAX_PROCESSING_AGE` to 150 would be the least intrusive fix.
