### ISSUE TITLE
CORS fails on devnet; preflight response doesn't allow the `content-type` header

### ISSUE THREAD

**Issue by bevanhunt** [solana-labs/solana#26341]
**Describe the bug**
When I use findReference from Solana Pay and the latest Wallet React library I get a CORS error on content-type not being allowed in the allowed headers.

**To Reproduce**
1. Use the Connection React Hook with DevNet set.
2. Call findReference from Solana Pay passing the connection from the hook.
3. The CORS call will fail with the allowed headers error.

**Expected behavior**
No CORS error should happen as with the last version of this library. The new version has this bug.

**Screenshots**
![Screen Shot 2022-06-29 at 7 30 02 AM](https://user-images.githubusercontent.com/892404/176462497-362ab929-a132-47ce-8abc-759b48cb7eac.png)

**Desktop (please complete the following information):**
Mac OS (latest beta) and also on Netlify

**Comment by jordansexton** [comment]
Is the issue with the devnet RPC config, then? What's actually triggering it, is it `connection.getRecentBlockhash()`?

**Comment by steveluscher** [comment]
Just literally any connection triggers it. The client asks for the devnet RPC to allow the `content-type` and `solana-client` headers, and the RPC responds by saying ‘OK you may use the `authorization` and `solana-client` headers.’

Seems like an indexing bug, like the proxy only planned for there to be one custom header and to copy that one over.

**Comment by steveluscher** [comment]
Try now, everyone.

**Comment by bevanhunt** [comment]
@steveluscher Works - thanks!

**Comment by xrei** [comment]
`const connection = new Connection(clusterApiUrl('devnet'), {
    commitment: 'confirmed',
  })`

this piece of code is not working on _"@solana/web3.js": "^1.47.0"_
and it is working on _"@solana/web3.js": "^1.44.0"_

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/9521710/176797069-2701fa6b-e648-408e-8556-b24007343440.png">

Headers from the latest version:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/9521710/176797137-56709137-def0-4333-be99-e838502cf6a4.png">

Headers from working 1.44.0 version:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/9521710/176797259-3b3af910-df42-4293-9b5c-e6af62847035.png">

**Comment by steveluscher** [comment]
It’s the response headers that we need to see to debug, @xrei. That said, I think Triton fixed the config of the RPC in the meantime. Try again!

**Comment by shadeglare** [comment]
The problem is still presented. Somehow the devnet server handles HTTP request headers in a case-sensitive way which indeed must be case-insensitive. Headers like `Content-Type` and `content-type` must be treated the same. At the moment the devnet server accepts only `content-type` in lower-case.

**Comment by steveluscher** [comment]
Thanks! I’ll get this fixed too.

**Comment by steveluscher** [comment]
@shadeglare, do you mean to say that when you send `Content-Type` in the request it:

1. doesn’t get reflected in the response at all, or
2. it gets reflected as `content-type`

**Comment by shadeglare** [comment]
@steveluscher I mean that a request with `Content-Type` will fail with the CORS error as described in the previous replies when `content-type` works just fine. So to send a valid request to the `devnet` network I have to use an older version of `@solana/web3.js` at least (1.44) which compose requests with the proper `content-type`.

**Comment by steveluscher** [comment]
Yeah! I totally get that, @shadeglare. I should have been more specific in my question: can you send me a screenshot of the request and response headers of your preflight request?

**Comment by steveluscher** [comment]
As well as the error on your console.

**Comment by shadeglare** [comment]
Request headers:
<img width="870" alt="Screenshot 2022-07-03 at 16 24 53" src="https://user-images.githubusercontent.com/995484/177041826-1ee87177-5c9a-4821-8a45-1b90254e97b7.png">
Console log:
<img width="842" alt="Screenshot 2022-07-03 at 16 24 27" src="https://user-images.githubusercontent.com/995484/177041827-22221ed9-b9af-4c67-a321-dae2faee9f25.png">
Hope it helps.

**Comment by steveluscher** [comment]
And one more, what about the response headers?

**Comment by steveluscher** [comment]
Specifically, can I see the request _and_ response headers from the request that says ‘preflight’ beside it; not the one that says POST.

**Comment by shadeglare** [comment]
<img width="421" alt="Screenshot 2022-07-03 at 18 59 47" src="https://user-images.githubusercontent.com/995484/177047628-fbfb4ed0-4821-40f8-b001-083843e45906.png">
<img width="429" alt="Screenshot 2022-07-03 at 18 59 56" src="https://user-images.githubusercontent.com/995484/177047626-674eaa33-bcf5-458a-931c-f1fcf003e4ff.png">

**Comment by steveluscher** [comment]
Got it. It looks like you’re hitting a box that didn’t get the new config. Can you do a traceroute for api.devnet.solana.com and tell me where you end up? https://dnschecker.org/online-traceroute.php

**Comment by shadeglare** [comment]
@steveluscher Just made a test and seems requests to `devnet` work correct. If there was a problem with a stale DNS config it's gone now. Thanks.
That's what it shows now.
<img width="938" alt="Screenshot 2022-07-04 at 09 17 56" src="https://user-images.githubusercontent.com/995484/177093126-f7c16f96-470a-4561-8b79-8d9a714d24ab.png">

**Comment by steveluscher** [comment]
No no, you helped us to find a node with a bad config. All fixed now! Thanks.

**Comment by luco** [comment]
Still getting this:
![image](https://github.com/solana-labs/solana/assets/246373/cc08993c-f2fa-43b2-a2db-8eb527eef21b)

**Comment by steveluscher** [comment]
I’m pretty sure that testnet is not authorized for access from localhost. cc/ @linuskendall
